repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^ngoconnect/.*\.py$
        args: ["--profile", "django"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["--skip", "B101,B601"]
        files: ^ngoconnect/.*\.py$